version: "3.9"

services:
  frontend:
    image: water-app-frontend:latest
    container_name: water-frontend
    ports:
      - "3000:80"
    volumes:
      # свой конфиг nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
